<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    
    <!-- Publish as Native AOT -->
    <PublishAot>true</PublishAot>
    
    <!-- Size optimizations for Native AOT -->
    <OptimizationPreference>Size</OptimizationPreference>
    <InvariantGlobalization>true</InvariantGlobalization>
    <StackTraceSupport>false</StackTraceSupport>
    <EventSourceSupport>false</EventSourceSupport>
    <UseSystemResourceKeys>true</UseSystemResourceKeys>
    <IlcTrimMetadata>true</IlcTrimMetadata>
  </PropertyGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>Hashi.UnitTests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

</Project>
