name: Build and Publish Docker Image

on:
  # Manual trigger
  workflow_dispatch:
  
  # Trigger on push to main branch, but only for relevant files
  push:
    branches:
      - main
    paths:
      - 'server.js'
      - 'src/**'
      - 'public/**'
      - 'package.json'
      - 'package-lock.json'
      - 'docker/Dockerfile'
      - '.gitea/workflows/docker-build.yml'
    # Explicitly ignore non-relevant files
    paths-ignore:
      - '*.md'
      - 'LICENSE'
      - '.gitignore'
      - 'config.yml'
      - 'docker-compose*.yml'

env:
  REGISTRY: git.juzo.io
  IMAGE_NAME: juzo/hashi

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            # Set latest tag for main branch
            type=raw,value=latest,enable={{is_default_branch}}
            # Tag with commit SHA
            type=sha,prefix=
            # Tag with version from package.json if tagged
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
          labels: |
            org.opencontainers.image.source=https://git.juzo.io/juzo/hashi
            org.opencontainers.image.description=Hashi - Homelab orchestration for Pangolin, Hetzner DNS, and Gatus
            org.opencontainers.image.licenses=MIT

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
