// <auto-generated />
using System;
using Hashi.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hashi.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(HashiDbContext))]
    [Migration("20260526082757_AddMonitorRollupIntervals")]
    partial class AddMonitorRollupIntervals
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0-preview.2.25163.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hashi.Infrastructure.Persistence.Entities.AbuseBucketEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClientIp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClientIp")
                        .IsUnique();

                    b.ToTable("abuse_buckets", (string)null);
                });

            modelBuilder.Entity("Hashi.Infrastructure.Persistence.Entities.AccessLogEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Asn")
                        .HasColumnType("text");

                    b.Property<string>("ClientIp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("CountryCode")
                        .HasColumnType("text");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReceivedAtUtc");

                    b.ToTable("access_log_events", (string)null);
                });

            modelBuilder.Entity("Hashi.Infrastructure.Persistence.Entities.AdGuardConnectionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("PasswordSecretId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("adguard_connections", (string)null);
                });

            modelBuilder.Entity("Hashi.Infrastructure.Persistence.Entities.AdGuardRewriteEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ConnectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("ManagedByHashi")
                        .HasColumnType("boolean");

                    b.Property<string>("ProviderRewriteId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ConnectionId", "Domain")
                        .IsUnique();

                    b.ToTable("adguard_rewrites", (string)null);
                });

            modelBuilder.Entity("Hashi.Infrastructure.Persistence.Entities.AppSettingsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminDomain")
                        .HasColumnType("text");

                    b.Property<int>("DefaultSyncIntervalMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("InternalUrl")
                        .HasColumnType("text");

                    b.Property<bool>("PublicDashboardEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("PublicStatusEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("RootDomain")
                        .HasColumnType("text");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("app_settings", (string)null);
                });

            modelBuilder.Entity("Hashi.Infrastructure.Persistence.Entities.AuditEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("text");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SubjectId")
                        .HasColumnType("text");

                    b.Property<string>("SubjectType")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.ToTable("audit_events", (string)null);
                });

            modelBuilder.Entity("Hashi.Infrastructure.Persistence.Entities.BlocklistEntryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClientIp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("SyncedToFirewall")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("blocklist_entries", (string)null);
                });

            modelBuilder.Entity("Hashi.Infrastructure.Persistence.Entities.ConnectionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletionPolicy")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("HealthState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("LastValidatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastValidationMessage")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("SecretId")
                        .HasColumnType("uuid");

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Type");

                    b.ToTable("connections", (string)null);
                });

            modelBuilder.Entity("Hashi.Infrastructure.Persistence.Entities.DnsImportDecisionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ProviderRecordId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("SelectedForImport")
                        .HasColumnType("boolean");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ZoneId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ZoneId");

                    b.ToTable("dns_import_decisions", (string)null);
                });

            modelBuilder.Entity("Hashi.Infrastructure.Persistence.Entities.DnsRecordEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Ownership")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ProviderRecordId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int?>("Ttl")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ZoneId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ZoneId");

                    b.ToTable("dns_records", (string)null);
                });

            modelBuilder.Entity("Hashi.Infrastructure.Persistence.Entities.DnsZoneEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConnectionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DefaultTtl")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ProviderZoneId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("ConnectionId");

                    b.ToTable("dns_zones", (string)null);
                });

            modelBuilder.Entity("Hashi.Infrastructure.Persistence.Entities.EdgeAuthRuleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("MatchJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("edge_auth_rules", (string)null);
                });

            modelBuilder.Entity("Hashi.Infrastructure.Persistence.Entities.FirewallHostEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConnectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InternalTraefikIp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastAppliedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastAppliedScriptHash")
                        .HasColumnType("text");

                    b.Property<string>("LinkedTraefikHost")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ManagedSubnetsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("NetBirdDetected")
                        .HasColumnType("boolean");

                    b.Property<string>("PublicIp")
                        .HasColumnType("text");

                    b.Property<string>("RollbackScript")
                        .HasColumnType("text");

                    b.Property<string>("ScriptPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ConnectionId", "Name")
                        .IsUnique();

                    b.ToTable("firewall_hosts", (string)null);
                });

            modelBuilder.Entity("Hashi.Infrastructure.Persistence.Entities.MonitorEndpointEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CheckType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastCheckedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastLatencyMs")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("ResourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("monitor_endpoints", (string)null);
                });

            modelBuilder.Entity("Hashi.Infrastructure.Persistence.Entities.MonitorRollupEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AverageLatencyMs")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("BucketStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DownCount")
                        .HasColumnType("integer");

                    b.Property<int>("IntervalMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid>("MonitorEndpointId")
                        .HasColumnType("uuid");

                    b.Property<int>("SampleCount")
                        .HasColumnType("integer");

                    b.Property<int>("UpCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MonitorEndpointId", "BucketStartUtc", "IntervalMinutes")
                        .IsUnique();

                    b.ToTable("monitor_rollups", (string)null);
                });

            modelBuilder.Entity("Hashi.Infrastructure.Persistence.Entities.MonitorSampleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CheckedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LatencyMs")
                        .HasColumnType("integer");

                    b.Property<Guid>("MonitorEndpointId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("PartitionDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MonitorEndpointId", "PartitionDate", "CheckedAtUtc");

                    b.ToTable("monitor_samples", (string)null);
                });

            modelBuilder.Entity("Hashi.Infrastructure.Persistence.Entities.NotificationProviderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.ToTable("notification_providers", (string)null);
                });

            modelBuilder.Entity("Hashi.Infrastructure.Persistence.Entities.OidcProviderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ClientSecretId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Scopes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("oidc_providers", (string)null);
                });

            modelBuilder.Entity("Hashi.Infrastructure.Persistence.Entities.PasskeyCredentialEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("CredentialId")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<byte[]>("PrfSalt")
                        .HasColumnType("bytea");

                    b.Property<bool>("PrfSupported")
                        .HasColumnType("boolean");

                    b.Property<byte[]>("PublicKey")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<long>("SignCount")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CredentialId")
                        .IsUnique();

                    b.ToTable("passkey_credentials", (string)null);
                });

            modelBuilder.Entity("Hashi.Infrastructure.Persistence.Entities.PulseAgentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("LastPublicIp")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.ToTable("pulse_agents", (string)null);
                });

            modelBuilder.Entity("Hashi.Infrastructure.Persistence.Entities.ResourceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DashboardEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Domain")
                        .HasColumnType("text");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("FirewallHostId")
                        .HasColumnType("uuid");

                    b.Property<string>("ForwardAuthPolicy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PathPrefix")
                        .HasColumnType("text");

                    b.Property<string>("PathRewrite")
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("StatusEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("TargetHost")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TargetPort")
                        .HasColumnType("integer");

                    b.Property<string>("TargetScheme")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WafMode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("resources", (string)null);
                });

            modelBuilder.Entity("Hashi.Infrastructure.Persistence.Entities.ScriptEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ConnectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("CronExpression")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastRunAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastRunOutput")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.ToTable("scripts", (string)null);
                });

            modelBuilder.Entity("Hashi.Infrastructure.Persistence.Entities.SecretRecordEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("AdminWrappedDekBlob")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("CiphertextBlob")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<byte[]>("ServiceWrappedDekBlob")
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Purpose");

                    b.ToTable("secret_records", (string)null);
                });

            modelBuilder.Entity("Hashi.Infrastructure.Persistence.Entities.SetupStateEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BootstrapPasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("BootstrapUsername")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("CompletedStepsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CurrentStep")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("HttpsDomainVerifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("setup_state", (string)null);
                });

            modelBuilder.Entity("Hashi.Infrastructure.Persistence.Entities.SyncDiffEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AfterJson")
                        .HasColumnType("text");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("text");

                    b.Property<string>("ChangeKind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResourceKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<Guid>("SyncRunId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SyncRunId");

                    b.ToTable("sync_diffs", (string)null);
                });

            modelBuilder.Entity("Hashi.Infrastructure.Persistence.Entities.SyncRunEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorSummary")
                        .HasColumnType("text");

                    b.Property<string>("RiskLevel")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Subsystem")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("StartedAtUtc");

                    b.ToTable("sync_runs", (string)null);
                });

            modelBuilder.Entity("Hashi.Infrastructure.Persistence.Entities.SyncStepEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SyncRunId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SyncRunId");

                    b.ToTable("sync_steps", (string)null);
                });

            modelBuilder.Entity("Hashi.Infrastructure.Persistence.Entities.TraefikHostStateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConnectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("DynamicConfigPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastAppliedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastAppliedContentHash")
                        .HasColumnType("text");

                    b.Property<string>("LastBackupDynamicYaml")
                        .HasColumnType("text");

                    b.Property<string>("LastBackupStaticYaml")
                        .HasColumnType("text");

                    b.Property<string>("StaticConfigPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ConnectionId")
                        .IsUnique();

                    b.ToTable("traefik_host_states", (string)null);
                });

            modelBuilder.Entity("Hashi.Infrastructure.Persistence.Entities.VaultWrappedKeyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PasskeyCredentialId")
                        .HasColumnType("uuid");

                    b.Property<string>("RecoveryKeyHash")
                        .HasColumnType("text");

                    b.Property<string>("WrapMethod")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<byte[]>("WrappedKeyBlob")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("PasskeyCredentialId");

                    b.HasIndex("WrapMethod");

                    b.ToTable("vault_wrapped_keys", (string)null);
                });

            modelBuilder.Entity("Hashi.Infrastructure.Persistence.Entities.DnsImportDecisionEntity", b =>
                {
                    b.HasOne("Hashi.Infrastructure.Persistence.Entities.DnsZoneEntity", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("Hashi.Infrastructure.Persistence.Entities.DnsRecordEntity", b =>
                {
                    b.HasOne("Hashi.Infrastructure.Persistence.Entities.DnsZoneEntity", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("Hashi.Infrastructure.Persistence.Entities.DnsZoneEntity", b =>
                {
                    b.HasOne("Hashi.Infrastructure.Persistence.Entities.ConnectionEntity", "Connection")
                        .WithMany()
                        .HasForeignKey("ConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Connection");
                });

            modelBuilder.Entity("Hashi.Infrastructure.Persistence.Entities.SyncDiffEntity", b =>
                {
                    b.HasOne("Hashi.Infrastructure.Persistence.Entities.SyncRunEntity", "SyncRun")
                        .WithMany("Diffs")
                        .HasForeignKey("SyncRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SyncRun");
                });

            modelBuilder.Entity("Hashi.Infrastructure.Persistence.Entities.SyncStepEntity", b =>
                {
                    b.HasOne("Hashi.Infrastructure.Persistence.Entities.SyncRunEntity", "SyncRun")
                        .WithMany("Steps")
                        .HasForeignKey("SyncRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SyncRun");
                });

            modelBuilder.Entity("Hashi.Infrastructure.Persistence.Entities.VaultWrappedKeyEntity", b =>
                {
                    b.HasOne("Hashi.Infrastructure.Persistence.Entities.PasskeyCredentialEntity", "PasskeyCredential")
                        .WithMany()
                        .HasForeignKey("PasskeyCredentialId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PasskeyCredential");
                });

            modelBuilder.Entity("Hashi.Infrastructure.Persistence.Entities.SyncRunEntity", b =>
                {
                    b.Navigation("Diffs");

                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
