// <auto-generated />
using Hashi.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hashi.Infrastructure.Persistence.Migrations;

[DbContext(typeof(HashiDbContext))]
partial class HashiDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "10.0.0-preview.2.25163.8");

        modelBuilder.Entity("Hashi.Infrastructure.Persistence.Entities.AppSettingsEntity", b =>
        {
            b.Property<int>("Id").HasColumnType("integer");
            b.Property<string>("AdminDomain").HasColumnType("text");
            b.Property<int>("DefaultSyncIntervalMinutes").HasColumnType("integer");
            b.Property<string>("InternalUrl").HasColumnType("text");
            b.Property<bool>("PublicDashboardEnabled").HasColumnType("boolean");
            b.Property<bool>("PublicStatusEnabled").HasColumnType("boolean");
            b.Property<string>("RootDomain").HasColumnType("text");
            b.Property<string>("Theme").IsRequired().HasMaxLength(32).HasColumnType("character varying(32)");
            b.Property<DateTimeOffset>("UpdatedAtUtc").HasColumnType("timestamp with time zone");
            b.HasKey("Id");
            b.ToTable("app_settings", (string)null);
        });

        modelBuilder.Entity("Hashi.Infrastructure.Persistence.Entities.AuditEventEntity", b =>
        {
            b.Property<Guid>("Id").HasColumnType("uuid");
            b.Property<string>("Action").IsRequired().HasMaxLength(128).HasColumnType("character varying(128)");
            b.Property<string>("Category").IsRequired().HasMaxLength(64).HasColumnType("character varying(64)");
            b.Property<DateTimeOffset>("CreatedAtUtc").HasColumnType("timestamp with time zone");
            b.Property<string>("MetadataJson").HasColumnType("text");
            b.Property<string>("Outcome").IsRequired().HasMaxLength(32).HasColumnType("character varying(32)");
            b.Property<string>("SubjectId").HasColumnType("text");
            b.Property<string>("SubjectType").HasColumnType("text");
            b.HasKey("Id");
            b.HasIndex("CreatedAtUtc");
            b.ToTable("audit_events", (string)null);
        });

        modelBuilder.Entity("Hashi.Infrastructure.Persistence.Entities.SetupStateEntity", b =>
        {
            b.Property<int>("Id").HasColumnType("integer");
            b.Property<string>("BootstrapPasswordHash").HasColumnType("text");
            b.Property<string>("BootstrapUsername").HasMaxLength(128).HasColumnType("character varying(128)");
            b.Property<string>("CompletedStepsJson").IsRequired().HasColumnType("text");
            b.Property<string>("CurrentStep").IsRequired().HasMaxLength(64).HasColumnType("character varying(64)");
            b.Property<bool>("IsComplete").HasColumnType("boolean");
            b.Property<DateTimeOffset>("UpdatedAtUtc").HasColumnType("timestamp with time zone");
            b.HasKey("Id");
            b.ToTable("setup_state", (string)null);
        });

        modelBuilder.Entity("Hashi.Infrastructure.Persistence.Entities.SyncDiffEntity", b =>
        {
            b.Property<Guid>("Id").HasColumnType("uuid");
            b.Property<string>("AfterJson").HasColumnType("text");
            b.Property<string>("BeforeJson").HasColumnType("text");
            b.Property<string>("ChangeKind").IsRequired().HasColumnType("text");
            b.Property<string>("ResourceKey").IsRequired().HasColumnType("text");
            b.Property<string>("ResourceType").IsRequired().HasColumnType("text");
            b.Property<Guid>("SyncRunId").HasColumnType("uuid");
            b.Property<string>("Summary").HasColumnType("text");
            b.HasKey("Id");
            b.HasIndex("SyncRunId");
            b.ToTable("sync_diffs", (string)null);
        });

        modelBuilder.Entity("Hashi.Infrastructure.Persistence.Entities.SyncRunEntity", b =>
        {
            b.Property<Guid>("Id").HasColumnType("uuid");
            b.Property<DateTimeOffset?>("CompletedAtUtc").HasColumnType("timestamp with time zone");
            b.Property<string>("ErrorSummary").HasColumnType("text");
            b.Property<string>("RiskLevel").HasColumnType("text");
            b.Property<DateTimeOffset>("StartedAtUtc").HasColumnType("timestamp with time zone");
            b.Property<string>("Status").IsRequired().HasMaxLength(32).HasColumnType("character varying(32)");
            b.Property<string>("Subsystem").IsRequired().HasMaxLength(64).HasColumnType("character varying(64)");
            b.HasKey("Id");
            b.HasIndex("StartedAtUtc");
            b.ToTable("sync_runs", (string)null);
        });

        modelBuilder.Entity("Hashi.Infrastructure.Persistence.Entities.SyncStepEntity", b =>
        {
            b.Property<Guid>("Id").HasColumnType("uuid");
            b.Property<DateTimeOffset?>("CompletedAtUtc").HasColumnType("timestamp with time zone");
            b.Property<string>("Message").HasColumnType("text");
            b.Property<string>("Name").IsRequired().HasColumnType("text");
            b.Property<DateTimeOffset>("StartedAtUtc").HasColumnType("timestamp with time zone");
            b.Property<string>("Status").IsRequired().HasColumnType("text");
            b.Property<Guid>("SyncRunId").HasColumnType("uuid");
            b.HasKey("Id");
            b.HasIndex("SyncRunId");
            b.ToTable("sync_steps", (string)null);
        });

        modelBuilder.Entity("Hashi.Infrastructure.Persistence.Entities.SyncDiffEntity", b =>
        {
            b.HasOne("Hashi.Infrastructure.Persistence.Entities.SyncRunEntity", "SyncRun")
                .WithMany("Diffs")
                .HasForeignKey("SyncRunId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
            b.Navigation("SyncRun");
        });

        modelBuilder.Entity("Hashi.Infrastructure.Persistence.Entities.SyncStepEntity", b =>
        {
            b.HasOne("Hashi.Infrastructure.Persistence.Entities.SyncRunEntity", "SyncRun")
                .WithMany("Steps")
                .HasForeignKey("SyncRunId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
            b.Navigation("SyncRun");
        });

        modelBuilder.Entity("Hashi.Infrastructure.Persistence.Entities.SyncRunEntity", b =>
        {
            b.Navigation("Diffs");
            b.Navigation("Steps");
        });
#pragma warning restore 612, 618
    }
}
